site_name: GraphBin
site_url: "https://github.com/Vini2/GraphBin"
site_author: "Vijini Mallawaarachchi"
repo_url: "https://github.com/Vini2/GraphBin"
repo_name: 'GitHub'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - HOME:
      - Introduction: index.md
      - Workflow: workflow.md
#      - Pipeline: pipeline.md
#      - Databases: databases.md
#      - Outputs: outputs.md
      - Citation: citation.md
    - RUNNING:
      - Install: install.md
      - Preprocess: preprocess.md
      - Usage: usage.md
      - Testing: testing.md
      - Support: support.md
      - Tutorial: tutorial.md
